name: Secure Build Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  # JOB 1: Security Scan (Checks for API Keys/Secrets)
  # If a secret is found, this job will now FAIL (Red X)
  security_scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified

  # JOB 2: Flutter Analyzer (Checks for Youssef's Syntax Errors)
  # If there is a typo or missing semicolon, this job will FAIL (Red X)
  flutter_check:
    name: Flutter Lint & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Check for Errors
        run: flutter analyze
